# Site settings
baseurl = "landrs-toolkit.github.io"
languageCode = "en-us"
title = "LANDRS"
theme = "syna"
enableGitInfo = true
version = "0.16.1"

# Google Analytics tracking
googleAnalytics = ""

[outputs]
  home = ["HTML", "JSON"]

[frontmatter]
date = ["date", "lastmod"]
lastmod = ["lastmod", ":git", "date"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
     unsafe = true

[params]
  name = "LANDRS"
  description = "Sloan Foundation funded project to build open source tools for managing scientific data on drones through the use of web standards and linked data technologies."

  [params.style]
    #background = "secondary"

  # Theme customizations
  # Assets relative to 'static/'
  [params.custom]
    favicon = "favicon.ico"
    favicon_ico_sizes = "16x16 32x32"
    favicon_png = "favicon.png"
    favicon_svg = "favicon.svg"

  # Piwik tracking
  [params.analytics.piwik]
    #url = ""
    #id = ""
    #domain = "" # Track subdomains via "*.example.com"
    # Optional hash for integrity check
    #hash = "sha512-RfeD0pacGTqy9m7U6PgehQfS4cc7SIt+e+P+H5e848kEvB/RW84CUGO3O4O3LNbxjevym6KPUZ8muPsMrI8WIw=="

  # Optional, global disable switch for fontawesome related files
  # For custom fontawesome js files use the custom.js method
  [params.fontawesome]
    disabled = false
    pro = false

  [params.colors]
    primary = "#ff6600" #Orange
    secondary = "#0066ff" #blue
    success = "#868e96"   #grey
    info = "#000066" #Darkblue
    warning = "#660066" #Maroone
    danger = "#dc1200"
    light = "#f8f9fa"
    dark = "#343a40"

# main/prepend/postpend menus are displayed in nav fragment.
# Keep an eye out for updates. These will be moved out to make navbar more
# configurable.
[[menu.main]]
  url = "/"
  name = "Home"
  weight = 10

[[menu.main]]
  url = "/about"
  name = "About Us"
  weight = 20

[[menu.main]]
  url = "/contact"
  name = "Contact"
  weight = 30

#[[menu.footer]]
#  url = "#"
#  name = "Link"
#  weight = 10
#
#[[menu.footer]]
#  url = "#"
#  name = "Long Link"
#  weight = 30
#
#[[menu.footer]]
#  url = "#"
#  name = "Tiny Link"
#  weight = 30

#[[menu.copyright_footer]]
#  url = "/about"
#  name = "About Us"
#  weight = 10

#[[menu.copyright_footer]]
#  url = "#"
#  name = "Another Link"
#  weight = 30

[[menu.footer_social]]
  weight = 20
  name = "Github"
  pre = "fab fa-github"
  url = "https://github.com/landrs-toolkit"

[[menu.footer_social]]
  weight = 30
  name = "Twitter"
  pre = "fab fa-twitter"
  url = "https://twitter.com/DroneData4Good"
